<h1> Curso 8

<h2> Ejercicio 4

Daniel González

Regresión Logística

In [3]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("prestamo.csv")
df.head()

Customer Id  Age  Edu  Years Employed  Income  Card Debt  Other Debt  \
0            1   41    2               6      19      0.124       1.073   
1            2   47    1              26     100      4.582       8.218   
2            3   33    2              10      57      6.111       5.802   
3            4   29    2               4      19      0.681       0.516   
4            5   47    1              31     253      9.308       8.908   

   Defaulted Address  DebtIncomeRatio  
0        0.0  NBA001              6.3  
1        0.0  NBA021             12.8  
2        1.0  NBA013             20.9  
3        0.0  NBA009              6.3  
4        0.0  NBA008              7.2

In [5]:
df.drop('Address', axis='columns', inplace=True)

In [6]:
df = df.dropna()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 700 entries, 0 to 849
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Customer Id      700 non-null    int64  
 1   Age              700 non-null    int64  
 2   Edu              700 non-null    int64  
 3   Years Employed   700 non-null    int64  
 4   Income           700 non-null    int64  
 5   Card Debt        700 non-null    float64
 6   Other Debt       700 non-null    float64
 7   Defaulted        700 non-null    float64
 8   DebtIncomeRatio  700 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 54.7 KB


In [8]:
feature_df = df[['Customer Id', 'Age', 'Years Employed', 'Income', 'Card Debt', 'Other Debt', 'Defaulted', 'DebtIncomeRatio']] .values  #.astype(float)
X = np.asarray(feature_df)
X[0:5]

array([[1.000e+00, 4.100e+01, 6.000e+00, 1.900e+01, 1.240e-01, 1.073e+00,
        0.000e+00, 6.300e+00],
       [2.000e+00, 4.700e+01, 2.600e+01, 1.000e+02, 4.582e+00, 8.218e+00,
        0.000e+00, 1.280e+01],
       [3.000e+00, 3.300e+01, 1.000e+01, 5.700e+01, 6.111e+00, 5.802e+00,
        1.000e+00, 2.090e+01],
       [4.000e+00, 2.900e+01, 4.000e+00, 1.900e+01, 6.810e-01, 5.160e-01,
        0.000e+00, 6.300e+00],
       [5.000e+00, 4.700e+01, 3.100e+01, 2.530e+02, 9.308e+00, 8.908e+00,
        0.000e+00, 7.200e+00]])

In [9]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-1.76624318,  0.76830405, -0.35900652, -0.72310225, -0.67569934,
        -0.60428433, -0.59494973, -0.58052847],
       [-1.76213049,  1.51908977,  2.64702891,  1.47870741,  1.43142147,
         1.5706204 , -0.59494973,  0.37222169],
       [-1.75801779, -0.23274357,  0.24220057,  0.30984549,  2.15411948,
         0.83520125,  1.68081427,  1.55949495],
       [-1.7539051 , -0.73326739, -0.65961006, -0.72310225, -0.41242741,
        -0.77383254, -0.59494973, -0.58052847],
       [-1.74979241,  1.51908977,  3.39853777,  5.6376812 ,  3.66521532,
         1.78065319, -0.59494973, -0.44860921]])

In [11]:
df['Edu'] = df['Edu'].astype('int')
y = np.asarray(df['Edu'])
y [0:5]

array([2, 1, 2, 2, 1])

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (560, 8) (560,)
Test set: (140, 8) (140,)


In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:35: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps,
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:597: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [14]:
yhat = LR.predict(X_test)
yhat

array([2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.24693372, 0.26767373, 0.18929636, 0.16125284, 0.13484335],
       [0.2973287 , 0.2090042 , 0.19090856, 0.1563576 , 0.14640094],
       [0.32596391, 0.22867852, 0.17303271, 0.13907517, 0.13324969],
       [0.30301416, 0.23811937, 0.16748802, 0.15730438, 0.13407408],
       [0.33298393, 0.22816742, 0.16571927, 0.14041927, 0.1327101 ],
       [0.33398739, 0.21890943, 0.17006633, 0.14418247, 0.13285438],
       [0.37767684, 0.20269417, 0.14773832, 0.13596664, 0.13592403],
       [0.30100717, 0.23122156, 0.17335513, 0.15947033, 0.13494581],
       [0.28324923, 0.23185914, 0.19457513, 0.15075499, 0.13956152],
       [0.30753293, 0.21788159, 0.18286281, 0.15408173, 0.13764093],
       [0.30328761, 0.24210472, 0.16396661, 0.15771287, 0.13292818],
       [0.26242185, 0.22681753, 0.20257348, 0.16846735, 0.13971979],
       [0.34872068, 0.2142729 , 0.15236531, 0.15027251, 0.1343686 ],
       [0.25914475, 0.24833646, 0.18501324, 0.16884664, 0.13865891],
       [0.29756776, 0.2321441 , 0.

In [16]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, yhat)

0.5857142857142857

In [22]:
print (classification_report(y_test, yhat))

              precision    recall  f1-score   support

           1       0.60      0.99      0.75        79
           2       0.25      0.06      0.09        36
           3       1.00      0.12      0.21        17
           4       0.00      0.00      0.00         5
           5       0.00      0.00      0.00         3

   micro avg       0.59      0.59      0.59       140
   macro avg       0.37      0.23      0.21       140
weighted avg       0.52      0.59      0.47       140

